### ISSUE TITLE
hide icon when drawer is disabled

### ISSUE THREAD

**Issue by Maikelv** [hydecorp/hydejack#166]
If no_drawer: true is set, and the page is not a cover, is it possible to hide the hamburger menu icon? Because in this case it does nothing when clicked.

**Comment by Gabryxx7** [comment]
In my case I simply added a CSS rule to `my-style.scss`:

```CSS
@media (min-width: 64em) {
  #_menu {
    display: none;
  }
}
```
