### ISSUE TITLE
Disable Dingbat

### ISSUE THREAD

**Issue by Wingysam** [hydecorp/hydejack#171]
Is there a way that I can disable the dingbat at the end of the post?

**Comment by qwtel** [comment]
Not right now but should be easy via custom css. Seems like a reasonable option to add in the future.

```css
hr.dingbat { display: none }
```
