### ISSUE TITLE
Liquid error: Cannot sort a null object

### ISSUE THREAD

**Issue by natashache** [hydecorp/hydejack#195]
I'm trying to add Hydejack pro as a gem theme to my jekyll project following the suggestion of https://github.com/hydecorp/hydejack/issues/164#issuecomment-526445722. 

However, the bundle failed to compile, with the following error:
```
bundle exec jekyll serve
Configuration file: /Users/Natasha/Documents/blog-site/_config.yml
            Source: /Users/Natasha/Documents/blog-site
       Destination: /Users/Natasha/Documents/blog-site/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
     Build Warning: Layout '404' requested in 404.md does not exist.
  Liquid Exception: Liquid error (line 4): Cannot sort a null object. in /_layouts/projects.html
```
Here's my config.yml file:
```
title: Blog
email: ''
description: >- # this means to ignore newlines until "baseurl:"
  Things and stuff.
baseurl: "" # the subpath of your site if applicable, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://example.com

# theme
theme: jekyll-theme-hydejack-pro

# Permalink format (/blog/ is ignored for pages)
permalink: /blog/:title

# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

# set to 'true' to enable Google Analytics tracking code in production builds
analytics: false

# Compress CSS
sass:
  style: compressed
  sass_dir: _sass

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

# set some common post defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name

# Build settings
markdown: kramdown

# Kramdown options
kramdown:
  # Prevent IDs from being added to h1-h6 tags
  auto_ids: false

# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
```
The root directory does not have `/_layouts/projects.html`, and I don't see anything wrong with the `/_layouts/projects.html` file under the './.hydejack-pro' folder.

@qwtel , any suggestions?
