### ISSUE TITLE
Recommendation, Add blur to sidebar 

### ISSUE THREAD

**Issue by ahmetozer** [hydecorp/hydejack#205]
I think adding blur to sidebar Is good option.
[Example](https://prnt.sc/s1smtn)

```css
.sidebar-bg::after {
    backdrop-filter: blur(5px);
}
```
