### ISSUE TITLE
How do you give filename for 'liquid' syntax code blocks?

### ISSUE THREAD

**Issue by LazyRen** [hydecorp/hydejack#268]
Rouge does provide syntax highlights for liquid;

Since liquid is used in html file, I tried both

* `<!-- file: "filename" -->`
  This simply doesn't work.
* `{% comment %} file: "filename" {% endcomment %}`
  The problem of this is that it is now interpreated as comment by jekyll.
  Tried putting {% raw %} before that, no luck.

**Comment by rriemann** [comment]
Try:

    ~~~sh
    # file: 'exclude.txt'
    src
    *i686.rpm
    *i686.drpm
    *i586.rpm
    ~~~

Note that the title must be in a comment line that follows the syntax of the respective language.

Source: https://hydejack.com/blog/hydejack/2021-02-13-whats-new-in-hydejack-9-1/#code-block-headers

**Comment by LazyRen** [comment]
My question is for the liquid syntax specific.

I can manage to work it with any other (except for default) syntaxes.

For example,

* yaml

~~~
```yaml
# file: "/_config.yml"
defaults:
  # You can use the following to enable comments on all posts.
  - scope:
      type:            posts
    values:
      # https://applause-button.com/
      applause_button:       true
```
~~~

* html
~~~
```html
<!-- file: "/_layouts/post.html" -->
{%- raw -%}
{% if page.applause_button %}
  <applause-button
    color={{ site.accent_color | default:'rgb(79,177,186)' }}
    url={{ site.url }}{{ page.url }} >
  </applause-button>
{% else %}
  <hr class="dingbat related" />
{% endif %}
{% endraw %}
```
~~~
