### ISSUE TITLE
assets & licenses folder are not excluded from sitemap.xml due to invalid value in _config.yml

### ISSUE THREAD

**Issue by LazyRen** [hydecorp/hydejack#278]
[hydejack-starter-kit/_config.yml file](https://github.com/hydecorp/hydejack-starter-kit/blob/e71915cd2187904ceee1372f8805a2dd635f01d3/_config.yml#L127) comes with below default setting.

```yml
  # Don't include documents in assets in the sitemap
  - scope:
      path:            assets/
    values:
      sitemap:         false

  - scope:
      path:            licenses/
    values:
      layout:          plain
      sitemap:         false
```

However, this does not prevent generated `sitemap.xml` to exclude contents of the folder.
You can actually see all the licenses folder from [starter-kit site's sitemap](https://hydecorp.github.io/hydejack-starter-kit/sitemap.xml).

To fix this, both path should add suffix `**` so the valid value would be

```yml
  # Don't include documents in assets in the sitemap
  - scope:
      path:            assets/**
    values:
      sitemap:         false

  - scope:
      path:            licenses/**
    values:
      layout:          plain
      sitemap:         false
```

Relevant info: https://stackoverflow.com/a/61302008/4294737
