### ISSUE TITLE
Is there a way to reduce the margin or padding on top of headers

### ISSUE THREAD

**Issue by harwinds** [hydecorp/hydejack#289]
Looking for a possible solution to reduce/decrease the margin or padding size above headings.

**Comment by qwtel** [comment]
Overwrite in `_sass/my-inline.scss`: 

```css
h1, h2, h3, .h1, .h2, .h3 {
  margin: 4rem 0 1rem;
}

h4, h5, h6, .h4, .h5, .h6 {
  margin: 3rem 0 .5rem;
}
```
