### ISSUE TITLE
[Question] How do I get overlay false while using an image as background?

### ISSUE THREAD

**Issue by prettygood236** [hydecorp/hydejack#299]
Thank you. but it do not work like the code below.

accent_image: 
  background: /assets/img/background/44-green-yellow.jpg
  overlay: false
or
accent_image: 
  url: /assets/img/background/44-green-yellow.jpg
  overlay: false
accent_image: 
  path: /assets/img/background/44-green-yellow.jpg
  overlay: false
  
How do I get overlay false while using an image as background?

**Comment by LazyRen** [comment]
Try this

```yaml
accent_image:
  background:          center / cover url(/assets/img/background/44-green-yellow.jpg)
  overlay:             false
```

if you can't make things work, taking a look at the code might help you. In this case, [sidebar-bg.html](https://github.com/hydecorp/hydejack/blob/master/_includes/body/sidebar-bg.html) is where you need to look.
