### ISSUE TITLE
Google serach pulls "hy" favicon

### ISSUE THREAD

**Issue by aepolin** [hydecorp/hydejack#331]
Hello, on google, and when texting a link to my website the "hy" favicon still appears as the logo even though I've replaced the favicon.ico and all pngs in my assets folder. I can not find a single instance of the original logo in my website directories but it still appears. Any ideas of how to fix this and replace with my favicon?

**Comment by tgaff** [comment]
Saw your issue and realized I had the same problem.

Try adding an apple_touch_icon per https://hydejack.com/docs/config/#changing-the-favicon (For my site this fixed the icon shown when sharing). 

You may also want to add some additional sharing/opengraph config for a larger image like:

```yaml
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/og_image.jpg

plugins:
  - jekyll-seo-tag
```
